# config.yaml
configs:
  - dbtype: mysql
    database: classicmodels
    host: localhost
    port: 3306
    users:
    - username: user1
      password: user1
    - username: user2
      password: user2

  # - database: postgres
  #   dbtype: postgres
  #   host: localhost
  #   port: 5432
  #   users:
  #   - username: user1
  #     password: user1
  #   - username: user2
  #     password: user2
    # - username: user3
    #   password: user3